FROM plantreg.azurecr.io/plants/windowsnodejs

RUN mkdir c:\\build\\ReceiveHubMessages
WORKDIR c:\\build\\ReceiveHubMessages

COPY . c:\\build\\ReceiveHubMessages
RUN npm install 

CMD [ "node", "index.js" ]


